### ISSUE TITLE
Seqplots heatmap

### ISSUE THREAD

**Issue by ghost** [Przemol/seqplots#14] opened 2016-05-10 05:14 UTC
When trying to create a heatmap in seqplots I am presented with this error: 
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘NSBS’ for signature ‘"list" 
Could you explain this error to me? do i need to change my table format

**Comment by Przemol** [comment] 2016-05-10 14:14
Duplicate of #11

Hi bgorsi, 
Thanks for feedback. I am working on solving this issue.

**Comment by bgorsi** [comment] 2016-05-10 15:54
Hi,
I get your example to work really nicely in seqplots. I have attached the two files I am using with danio-rerio genome. Let me know if you can reproduce the error?
Second bed graph file will be sent in a separate email since file is too big.

Bushra

**Comment by Przemol** [comment] 2016-06-29 17:05
Fixed in 341508d135c44238873c962eff23fde73820884f

**Closed by Przemol** 2016-06-29 17:05 UTC
Labels: duplicate
